export interface Itineary {
    packagetype:string,
      raisedate:string,
      itinerary:string,
      formraiser:string,
      partnerdetails:string,
      refno: string,
      type:string,
      pdf:string,
      excel:string,
      customertype: string,
      customername:  string,
      customernumber:  number,
      customerlocation: string,
      destination: string,
      startfrom: string,
      sourcename: string,
      sourcerole: string,
      preferfrom: string,
      preferto: string, 
      travelflex: string,
      cities: string,
      tripdate:string,
      enddate:string,
      duration: string,
      passenger: number,
      child: number,
      adults: number,
      infant: number,
      hstandard: string,
      htype: string,
      roomtype: string,
      hpreference: string,
      numofrooms: string,
      specific: string,
      meal: string,
      foodpreferences: string,
      specificreq: string,
      specifictour: string,
      comments: string,
      createdAt: Date
}
